### ISSUE TITLE
usage questiom

### ISSUE THREAD

**Issue by schoko11** [MVS-sysgen/web3270#1]
Hi,
thank you for this project!

I am not really sure if this can be used in conjunction with a real z/os mainframe. (a html based 3270 without the need of a windows terminal app would be really nice).

**Comment by mainframed** [comment]
Why couldn't it be used with z/os? You could just run the container: https://hub.docker.com/r/mainframed767/web3270

**Comment by kraabrsg** [comment]
Hi @mainframed , sorry for asking questions on this topic again, trying to use your docker image.
It is a fairly new topic to me.

So i am on WIN10 (having also docker desktop installed) 

`
docker run -d --name=web3270 -p 4443:[MVS_PORT] --restart unless-stopped mainframed767/web3270
`
Because i can't install nano, due to site policy restrictions i used
`
docker cp 
`
to copy out web3270.ini, edit it, and then copying back in the container.

I could successfully connect to a "S3270" or "WC3270" with
`
wc3270.hostname: L:Y:[MVSHOSTNAME]:[MVSPORT]
`
According to https://x3270.miraheze.org/wiki/Wx3270/Help/ConnectionEditor  (Create TLS tunnel, Verify host Certificate)


My /config/web3270.ini looks like 
```
[tn3270]
server_ip = [MVSIP]
server_port = [MVSPORT]
; should the connection be encrypted
encrypted = yes
; enables -noverifycert
selfsignedcert = yes
; tn3270 model type
model = 5
; to use proxies change below to yes and uncomment the proxystring
; and adjust as needed
useproxy = no
;proxystring = socks5d:fred:secret@localhost:12345

[web]
webport = 443
;tls = no
```

(confusingly docker desktop is showing port 4443) -> but wether on http://localhost:443/  or http://localhost:4443/ anything shows up

docker ps (PORTS):
`
80/tcp, 443/tcp, 0.0.0.0:4443->[mvsport]/tcp, :::4443->[mvsport]/tcp
`

1.) why can't i connect on localhost ?
2.) can i use the mvshost name  ?

Thank you!

**Comment by mainframed** [comment]
It looks like you're pointing the localhost port 4443 to some other IP address port and not the port of the web server running. Try: `ocker run -d --name=web3270 -p 4443:443 --restart unless-stopped mainframed767/web3270` and connecting to `https://<docker_ip_address>:4443`

**Comment by kraabrsg** [comment]
yes you are right that was my error with the ip in the docker run command, but it still does not work.

PORTS:
`
80/tcp, 0.0.0.0:4443->443/tcp, :::4443->443/tcp
`
when clicking "open in browser" in docker desktop it opens up without https???

i could somehow connect but then...

![grafik](https://user-images.githubusercontent.com/86772851/149486734-a5ae3112-4ecc-4c0c-8880-b2bdeca2241c.png)


[EDIT]: 
well finally i had to remove secret = 

![grafik](https://user-images.githubusercontent.com/86772851/149497262-49978010-39a7-4601-8831-cc322663245e.png)

Thanks! (now i just need to access it from vscodium)

Could i use e.g. a server hostname ?
